GROUP_REPOS = [
    [
        "group a",
        "ZeroDownTime",
        ["https://github.com/ZeroDownTime-ITU/minitwit_project"],
        "https://zerodt.live/",
        "http://zerodt.live/api",
    ],
    [
        "group b",
        "catch(RuntimeException){goto f;}",
        ["https://github.com/JohannesHackl/DevOps26_RE_minitwit"],
        "https://runtimetwiterror.dev",
        "https://runtimetwiterror.dev/api",
    ],
    [
        "group c",
        "group c",
        ["https://github.com/jskoven/Devops2026_jklo_jakst_aing_asjo_mbln"],
        "http://161.35.68.148:80",
        "http://161.35.68.148:80",
    ],
    [
        "group d",
        "Dense Dino Nuggets",
        ["https://github.com/Slug-Boi-ITU-Repositories/Dense-Dino-Nuggets"],
        "http://164.92.201.201:8080",
        "http://164.92.201.201:8080",
    ],
    [
        "group e",
        "Jams",
        ["https://github.com/sebsthiel/minitwit-devops"],
        "https://minitwit-devops.tech",
        "https://minitwit-devops.tech/api"
    ],
    [
        "group f",
        "if time > 16 {beer++;}",
        ["https://github.com/TienCamLy/MiniTwit"],
        "http://157.230.30.175:8080",
        "http://157.230.30.175:8080",
    ],
    [
        "group g",
        "DevOpps",
        ["https://git.marfavi.com/DevOpps/minitwit"],
        "https://minitwitter.com",
        "https://minitwitter.com/api",
    ],
    [
        "group i",
        "I Terroni",
        ["https://github.com/stegish/I-Terroni-DevOps"],
        "http://164.92.231.30:8080",
        "http://164.92.231.30:8080",
    ],
    [
        "group k",
        "Pat Myaz",
        ["https://github.com/ITU-DevOps2026/ITU-minitwit"],
        "https://bigtwit.app",
        "https://bigtwit.app/api",
    ],
    [
        "group m",
        "Holy C Enjoyers",
        ["https://github.com/MudiLoodi/minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group n",
        "Diversity",
        ["https://github.com/huncut47/diversity"],
        "https://kulturbase.dk",
        "https://kulturbase.dk",
    ],
    [
        "group o",
        "Rollback & Relax",
        ["https://github.com/alqeren1/devops"],
        "http://167.172.111.97:3000",
        "http://167.172.111.97:5001",
    ],
    [
        "group p",
        "EastTops",
        ["https://github.com/AntohaY/itu-minitwit"],
        "https://itu-minitwit.me/",
        "https://itu-minitwit.me/",
    ],
    [
        "group q",
        "DevTroopers",
        ["https://github.com/DevTroopers-ITU/itu-minitwit"],
        "https://devtroopersminitwit.codes/",
        "https://devtroopersminitwit.codes/",
    ],
]
